platform :ios, '9.3'

use_frameworks!

target 'AnobiKit_Example' do
  pod 'AnobiKit', :path => '../'

  target 'AnobiKit_Tests' do
      #pod 'AnobiKit', '~> 0.10.3', :testspecs => ['Tests']
      inherit! :search_paths
      #inherit! :complete
  end
end
